---
ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab_asiri-devops

plugin: netbox.netbox.nb_inventory
validate_certs: false
config_context: false

data_dir: '{{ lookup("env", "NETBOX_CONFIG_FILES_DIR") }}'
