- name: Read IP Prefix Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: ip_prefixes.yaml
    name: config
  tags: ipam

- name: Create IP Prefixes
  netbox.netbox.netbox_prefix:
    data: "{{ prefix }}"
    state: present
  loop: "{{ config['ip_prefixes'] }}"
  loop_control:
    loop_var: prefix
    label: "{{ prefix['prefix'] }}"
  tags: ipam
