- name: Read VLAN Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: vlan.yaml
    name: config
  tags: vlan

- name: Create VLAN's
  netbox.netbox.netbox_vlan:
    data: "{{ vlan }}"
    state: present
  loop: "{{ config['vlans'] }}"
  loop_control:
    loop_var: vlan
    label: "{{ vlan['name'] }}"
  tags: vlan
