- name: Create Devices
  gather_facts: false
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  hosts: localhost
  roles:
    - create_devices ## creates device with management ip's, interfaces etc.
