---
- name: Setup Organization Data
  gather_facts: false
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  hosts: localhost
  roles:
    - create_regions
    - create_sites
    - create_locations
    - create_racks

- name: Setup Basic Data
  gather_facts: false
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  hosts: localhost
  roles:
    - create_manufacturers
    - create_device_roles
    - create_device_types
