- name: Read Rack Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: racks.yaml
    name: config

- name: Create Racks
  netbox.netbox.netbox_rack:
    data: "{{ rack }}"
    state: present
  loop: "{{ config['racks'] }}"
  loop_control:
    loop_var: rack
    label: "{{ rack['name'] }}"
