- name: Read Location Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: locations.yaml
    name: config

- name: Create Locations
  netbox.netbox.netbox_location:
    data: "{{ location }}"
    state: present
  loop: "{{ config['locations'] }}"
  loop_control:
    loop_var: location
    label: "{{ location['name'] }}"
# - name: Show Content
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop: "{{ config['locations'] }}"
#   loop_control:
#     label: "{{ item['name'] }}"

# - name: Load Locfigs
#   ansible.builtin.find:
#     paths: data
#     patterns: "locations.yaml"
#     recurse: false
#   register: file_list

# - name: Show Content
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop: "{{ file_list.files | map(attribute='path') | list }}"

# - name: Show Content
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop: "{{ file_list.files | map(attribute='path') | list }}"
