---
- name: Read Sites Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: sites.yaml
    name: config

- name: Create Sites
  netbox.netbox.netbox_site:
    data: "{{ site }}"
    state: present
  loop: "{{ config['sites'] }}"
  loop_control:
    loop_var: site
    label: "{{ site['name'] }}"
