---
- name: Read Device Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: devices.yaml
    name: config

- name: Create Device
  netbox.netbox.netbox_device:
    data: "{{ device }}"
    state: present
  loop: "{{ config['devices'] }}"
  loop_control:
    loop_var: device
    label: "{{ device['name'] }}"
