---
- name: Read Device Roles Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: device_roles.yaml
    name: config

- name: Create Device Roles
  netbox.netbox.netbox_device_role:
    data: "{{ role }}"
    state: present
  loop: "{{ config['device_roles'] }}"
  loop_control:
    loop_var: role
    label: "{{ role['name'] }}"
