---
- name: Read Device Types Config File
  ansible.builtin.include_vars:
    dir: "{{ data_dir }}"
    files_matching: device_types.yaml
    name: config

- name: Create Locations
  netbox.netbox.netbox_device_type:
    data: "{{ type }}"
    state: present
  loop: "{{ config['device_types'] }}"
  loop_control:
    loop_var: type
    label: "{{ type['model'] }}"
